#+begin cv_config  AwesomeCV and LaTeX configuration section

# AwesomeCV configuration options
# #+photo: ./images/foto_diego.png
#+photostyle: right,noedge
#+cvcolor: awesome-orange
#+cvfooter_left: \today
#+cvfooter_middle: %a~~~·~~~Curriculum Vit\ae
#+cvfooter_right: \thepage

# These options are useful for HTML or ASCII export, and harmless for
# AwesomeCV, so I leave them on all the time
#+options: num:1
#+options: prop:("FROM" "TO" "LOCATION" "EMPLOYER" "SCHOOL" "ORGANIZATION" "DATE" "POSITION" "LABEL")
#+options: toc:nil

# LaTeX options

#+latex_class_options: [12pt,a4paper]

# Macro for bibliographical citations
#+macro: cvcite \cite{$1}

# Commands for including the Publications list using biblatex
# defernumbers=true makes the "Publications" section label the entries
# consecutively, instead of in some semi-random order determined by LaTeX.
#+latex_header: \usepackage[defernumbers=true,style=numeric,sorting=ydnt]{biblatex}
#+latex_header: \addbibresource{zamboni-pubs.bib}
#+latex_header: \addbibresource{zamboni-patents.bib}
#+latex_header: \defbibheading{cvbibsection}[\bibname]{\cvsubsection{#1}}

# Some font and separator redefinitions for the AwesomeCV class
#+latex_header: \renewcommand{\acvHeaderSocialSep}{\quad\cdotp\quad}
#+latex_header: \renewcommand{\acvHeaderIconSep}{~}
#+latex_header: \renewcommand*{\bodyfontlight}{\sourcesanspro}
#+latex_header: \renewcommand*{\bibfont}{\paragraphstyle}
#+latex_header: \renewcommand*{\entrylocationstyle}[1]{{\fontsize{10pt}{1em}\bodyfontlight\slshape\color{awesome} #1}}
#+latex_header: \renewcommand*{\subsectionstyle}{\entrytitlestyle}

#+end

#+title: IT Enterprise Security Architect · CFEngine Expert · Team and Project Leader
#+author: Diego Zamboni
#+email: diego@zzamboni.org
#+twitter: zzamboni
#+linkedin: zzamboni
#+github: zzamboni
#+stackoverflow: 5562 zzamboni
#+homepage: zzamboni.org

#+begin_comment --- How to include private information in the CV ---

The "Private info" section contains private information which should not be included in the CV by default. It is kept encrypted automatically thanks to the org-crypt package, whose configuration you can see here: https://github.com/zzamboni/dot-emacs/blob/master/init.org#encryption. The "crypt" tag causes it to be encrypted automatically every time the file is saved, and the "noexport" tag causes it to be omitted when the file gets exported. Its contents, when unencrypted, contains field definitions like this:

,#+mobile: <my mobile number>
,#+address: <my address>
,#+extrainfo: <other private information>

When encrypted, this information is simply ignored. When I want to produce a version of my CV which includes this information, I run ~M-x org-decrypt-entry~, which prompts for my GPG passphrase. Then, *without saving the file*, I run the following export command:

(org-export-to-file 'awesomecv "zamboni-vita-private.tex")

#+end_comment
* Private info :noexport:crypt:
-----BEGIN PGP MESSAGE-----
Comment: GPGTools - http://gpgtools.org

hQEMA6qprSR9RgU9AQgAiQGiKSOuTSMuTUQIU9Xqo4dczmdlInE2Dn3/G2/ADDbd
+ZTgiPa+W8GBMezuTWCXvJLJq+OBai2z/DxazsRjN2q/6QKiLBM0gbWqqQHUCwIP
5585zDInSO4HGoUPgjIqyPnPMuQWcMzhmI9OxuBe5QvLVFdFTk/7bmDcdqK3vccb
qnApDl7akZcBFST7nVh3bW5OkHQ8JtNVPqorP4ZkwYPVKKwgXm815BpxMspT03sz
yEUKkpi93S97Jd/SFZvgrMYFoKQhlZhij4Hgl8DiqIJ20v/CK6mKBIPXjuIoaQgM
K6FZaY0ln8+aw+7KPPnDeHRkuWyCFcDI9XHfXbK0JNKxAThCWMuhTM/1HSP6uFWJ
9dckj2SRWDeIy6upinvEBVFkdkOs6vEg9tzFSI4KvBDR7PmwkCt8WXTE2EWTvx9X
GKHO/iWilFg/d5SeR34TxmFlMRm/8uRa9hVXyHceJAq+9qAWo1cf5PRO6UlQDOw3
Rw6fltyGf36lnki4VHgl5VtcnnRR4x7hkjPGuZ41piOupdNJPdSllIxU+MgsZDei
f/yLKNfJQJz6Y3WA/L6QqNVO
=wzUV
-----END PGP MESSAGE-----

* Table of Contents                                          :TOC_3:noexport:
- [[#introduction][Introduction]]
- [[#skill-and-experience-overview][Skill and Experience Overview]]
- [[#experience][Experience]]
  - [[#swisscom][Swisscom]]
    - [[#enterprise-security-architect--it-clouds-security-solution-architect][Enterprise Security Architect / IT Clouds Security Solution Architect]]
    - [[#squad-lead--product-owner-for-health--state-management-in-the-it-clouds-large-solution][Squad Lead & Product Owner for Health & State Management in the IT Clouds Large Solution]]
    - [[#squad-lead--product-owner-for-health--state-management-in-the-enterprise-service-cloud-project][Squad Lead & Product Owner for Health & State Management in the Enterprise Service Cloud project]]
    - [[#head-of-health-and-state-management][Head of Health and State Management]]
    - [[#lemm-squad-lead-in-the-enterprise-cloud-project][LEMM Squad Lead in the Enterprise Cloud project]]
    - [[#cloud-architect-and-orchard-project-lead][Cloud Architect and Orchard Project Lead]]
  - [[#swisscom-cloud-lab][Swisscom Cloud Lab]]
    - [[#senior-platform-architect][Senior Platform Architect]]
  - [[#cfengine-as][CFEngine AS]]
    - [[#product-manager][Product Manager]]
    - [[#senior-security-advisor][Senior Security Advisor]]
  - [[#hp-enterprise-services][HP Enterprise Services]]
    - [[#account-security-officer][Account Security Officer]]
    - [[#it-outsourcing-service-delivery-consultant][IT Outsourcing Service Delivery Consultant]]
  - [[#ibm-zurich-research-lab][IBM Zurich Research Lab]]
    - [[#research-staff-member][Research Staff Member]]
  - [[#sun-microsystems][Sun Microsystems]]
    - [[#developer-intern][Developer (Intern)]]
  - [[#national-autonomous-university-of-mexico-unam][National Autonomous University of Mexico (UNAM)]]
    - [[#head-of-computer-security-area][Head of Computer Security Area]]
    - [[#system-administrator][System Administrator]]
- [[#education][Education]]
  - [[#phd-in-computer-science][Ph.D. in Computer Science]]
  - [[#ms-in-computer-science][M.S. in Computer Science]]
  - [[#bachelors-degree-in-computer-engineering][Bachelor's degree in Computer Engineering]]
- [[#certifications][Certifications]]
  - [[#certified-information-systems-security-professional-cissp][Certified Information Systems Security Professional (CISSP)]]
  - [[#safereg-4-certified-product-ownerproduct-manager][SAFe\reg 4 Certified Product Owner/Product Manager]]
- [[#system-development-and-management][System Development and Management]]
- [[#software-development-projects][Software Development Projects]]
  - [[#publicly-available-software-projects-see-httpsgithubcomzzamboni][Publicly-available software projects: see https://github.com/zzamboni/]]
  - [[#other-software-projects-not-publicly-available][Other software projects (not publicly available)]]
    - [[#pilatus-ibm][Pilatus (IBM)]]
    - [[#soc-in-a-box-ibm][SOC in a Box (IBM)]]
    - [[#billy-goat-ibm][Billy Goat (IBM)]]
    - [[#embedded-sensors-project-esp][Embedded Sensors Project (ESP)]]
- [[#references][References]]

* Introduction

#+latex: \begin{cvparagraph}
I am a senior computer security expert, IT architect, computer scientist, team and project leader with 29 years of professional experience. I specialize in the areas of Configuration Management, Computer Security, Cloud Computing and Self-healing Systems. I possess a strong combination of leadership, research and technical skills that enable me to lead teams in analyzing complex problems, designing and implementing elegant and pragmatic solutions. I have strong communication abilities, with ample experience in writing, teaching and public speaking. I can interact and work fluently at the strategic, tactical and technical levels. I have a Ph.D. in Computer Science and have experience in both academic and business environments.
#+latex: \end{cvparagraph}

* Skill and Experience Overview
:PROPERTIES:
:CV_ENV:   cvskills
:END:

- Configuration management :: CFEngine (Author of [[https://cf-learn.info/][/Learning CFEngine/]]), Ansible, Puppet.
- Computer Security :: Enterprise Security Architecture, Intrusion detection and prevention (Ph.D. in Computer Science in this area), operating systems security, network security, software security, secure software development, virtualization and cloud computing security, malware detection and containment.
- Leadership :: Technical team and project leadership, [[https://www.scaledagile.com/][Scaled Agile Framework (SAFe)]] methodology and processes, SAFe Product Owner certification, SAFe Architect training.
- Systems and Development :: Unix/Linux systems engineering and administration, systems health management and monitoring, cloud computing environments and platforms (OpenStack, Amazon EC2, Cloud Foundry) and software development experience (C, Python, Ruby, Perl, Java, etc.).
- Communications :: Excellent written and spoken communication skills, with more than 30 years of  written and oral communication and teaching experience in different contexts and topics.
- Languages :: Spanish (native), English (100%), German (B1/B2 level).
- Other skills :: Customer-facing experience, project and product management experience.

* Experience
:PROPERTIES:
:CV_ENV:   cventries
:END:

** Swisscom
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: Switzerland
:FROM: 2015
:END:

*** Enterprise Security Architect / IT Clouds Security Solution Architect
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: <2019-04-01>
:END:

- As Enterprise Architect, I participate in the design of the future products and solutions offered by Swisscom.
- As Security Architect for the IT Clouds Large Solution, I design and define security-relevant product features, compliance and business goals of the cloud platforms built by Swisscom. I also advise on compliance, governance and operational activities. Selected achievements:

*** Squad Lead & Product Owner for Health & State Management in the IT Clouds Large Solution
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: <2018-04-01>
:TO: <2019-04-01>
:END:

- I oversaw the requirement definition, planning and execution of the HSM team's mission to design, implement and manage Health Management and Monitoring components for all the IT Clouds platforms, including Enterprise Service Cloud, Application Cloud, Enterprise Cloud 1.x, Enterprise Cloud for SAP applications (EC4SAP), Marketplace Services, and Cloud Connectivity Management.
- Main technologies involved: VMware vSphere (ESX, vCenter, NSX), VMware vRealize Operations Manager and Log Insight, Ansible (configuration management), OpsGenie (alert management).

*** Squad Lead & Product Owner for Health & State Management in the Enterprise Service Cloud project
:PROPERTIES:
:CV_ENV:   cvsubentry
:EMPLOYER: Swisscom
:LOCATION: Switzerland
:FROM: <2017-01-01>
:TO: <2018-03-01>
:END:

- Worked with Product Management to define the technical features necessary for Health Management and Monitoring in the Enterprise Service Cloud project
- I lead the team which implements, deploys and operates these components.

*** Head of Health and State Management
:PROPERTIES:
:CV_ENV:   cvsubentry
:EMPLOYER: Swisscom
:LOCATION: Switzerland
:FROM: <2016-03-01>
:TO: <2017-01-01>
:END:

- Led a team working on multiple projects related to Health Management and Monitoring of the Swisscom cloud offerings, including Application Cloud (CloudFoundry-based PaaS offering), Enterprise Cloud 1.x and Enterprise Service Cloud (IaaS offerings).

*** LEMM Squad Lead in the Enterprise Cloud project
:PROPERTIES:
:CV_ENV:   cvsubentry
:EMPLOYER: Swisscom
:LOCATION: Switzerland
:FROM: <2016-06-01>
:TO: <2016-12-31>
:END:

- Led the architecture and delivery of the Logging, Event Management and Monitoring framework (LEMM) of the Swisscom Enterprise Cloud, which handles all the processing, analysis and monitoring of the logging messages, health events, and other relevant infrastructure events.

*** Cloud Architect and Orchard Project Lead
:PROPERTIES:
:CV_ENV:   cvsubentry
:EMPLOYER: Swisscom
:LOCATION: Switzerland
:FROM: <2015-08-01>
:TO: <2016-03-01>
:END:

- Continued leading the /Orchard/ project through its implementation, release and further improvements and development.

** Swisscom Cloud Lab
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: U.S.A. (remote)
:FROM: 2014
:TO: 2015
:END:

*** Senior Platform Architect
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: <2014-08-01>
:TO: <2015-07-31>
:END:

- I designed the architecture for the /Orchard/ health-management and self-healing components of Swisscom's /Application Cloud/ Platform-as-a-Service Offering. This system performs self-monitoring and self-healing of the infrastructure and platform components. In addition to designing the architecture, I worked on its implementation together with a team of three people managed by me.
- Main technologies involved: OpenStack (cloud computing infrastructure), Plumgrid (SDN), Cloud Foundry (application platform), Consul (health management and service discovery), RabbitMQ (message bus), Riemann (event stream analysis).

** CFEngine AS
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: Norway/U.S.A. (remote)
:FROM:     2011
:TO:       2014
:END:

*** Product Manager
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM:     <2013-08-01>
:TO: <2014-06-30>
:END:

- Coordinated the [[http://cfengine.com/cfengine-design-center/][CFEngine Design Center]] project.
- Participated in the development of the CFEngine language roadmap.
- Coordinated the work on CFEngine third-party integration  (e.g. AWS EC2, VMware, Docker and OpenStack).
- Developed code for both the Design Center and some of the integrations.

*** Senior Security Advisor
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM:     <2011-10-01>
:TO: <2014-06-30>
:END:

- Overall advocate and fanatic for CFEngine, with a special focus on security.
- Gave talks, wrote articles and blog posts, taught classes, and in general spread the word about CFEngine.
- Worked on developing and implementing the strategy for CFEngine in security.

** HP Enterprise Services
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: Mexico
:FROM:     2009
:TO:       2011
:END:

*** Account Security Officer
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: <2010-10-01>
:TO: <2011-10-01>
:END:

-  I was the first point of contact for all security-related issues for five HP enterprise customers in Mexico, some of them with international presence.
-  Initiated, advised and managed security-related projects.
-  Handled communication and coordination between technical teams involved in security initiatives.
-  Involved in all security-related decisions at the sales, design, implementation, delivery and ongoing maintenance stages of IT Outsourcing projects.

*** IT Outsourcing Service Delivery Consultant
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: <2009-11-01>
:TO: <2010-10-01>
:END:

- I helped customer teams by solving complex problems in customer environments.
- Performed analysis, design and implementation of solutions in multiple areas of expertise, including system automation, configuration management, system administration, system design, virtualization, performance and security.

** IBM Zurich Research Lab
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: Switzerland
:FROM:     2001
:TO:       2009
:END:

*** Research Staff Member
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM:     <2001-10-01>
:TO:       <2009-10-01>
:END:

- I worked in intrusion detection, malware detection and containment, and virtualization security research projects. See /Research activities/ for details of my research.

** Sun Microsystems
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: U.S.A.
:FROM:     1997
:TO:       1997
:END:

*** Developer (Intern)
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM:     <1997-05-01>
:TO:       <1997-08-01>
:END:

- Participated in the development of the /Bruce/ host vulnerability scanner, later released as the [[http://www.usenix.org/publications/login/1999-11/features/senss.html][Sun Enterprise Network Security Service]] (SENSS).
- Designed and implemented the first version of the network-based components of /Bruce/, which allowed it to operate on several hosts in a network, controlled from a central location.

** National Autonomous University of Mexico (UNAM)
:PROPERTIES:
:CV_ENV:   cvemployer
:LOCATION: Mexico
:FROM:     1991
:TO:       1996
:END:

*** Head of [[http://www.seguridad.unam.mx/][Computer Security Area]]
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM:     <1995-08-01>
:TO:       <1996-08-01>
:END:

- Founded UNAM's [[http://www.seguridad.unam.mx/][Computer Security Area]], the University's first team dedicated to computer security, which has since evolved into a much larger organization.
- Supervised up to nine people working on different projects related to computer security.
- Supervised and participated in the direct monitoring of the security of a Cray supercomputer and 22 Unix workstations.
- Provided security services to the whole University, including incident response, security information, auditing and teaching.
- Established the celebration of the /International Computer Security Day/ (sponsored by the Association for Computing Machinery) at UNAM.  Acted as the main organizer of the event for two years (1994 and 1995). This event has grown and divided into the /Computer Security Day/ (a one-day event) and the /Seguridad en Cómputo/ (Computer Security) conference (a multi-day event).
- Designed and headed development of an audit-analysis tool for Unix systems (SAINT).

*** System Administrator
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM:     <1991-11-01>
:TO:       <1995-08-01>
:END:

- Part of the system administration team at the University's Supercomputing Center, managing UNAM's [[http://www.historiadelcomputo.unam.mx/files/fotos/Cray/cray.html][Cray Y-MP Supercomputer]] (the first supercomputer in Latin America) and related systems.
- Managed the Network Queuing Subsystem (NQS).
- Collaborated in other aspects of the supercomputer administration, including user administration, operating system installation, resource management, and policy making and implementation.
- Directly managed three Unix workstations, provided support for 19 more.
- Monitored the security of the Cray supercomputer and related workstations.

* Education
:PROPERTIES:
:CV_ENV:   cventries
:END:

** Ph.D. in Computer Science
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: West Lafayette, IN, U.S.A.
:SCHOOL: Purdue University
:FROM: <1996-08-01>
:TO: <2001-08-01>
:END:

- Thesis title: [[https://zzamboni.org/files/theses/zamboni-phd-thesis.pdf][/Using Internal Sensors for Computer Intrusion Detection/]].
- Advisor: [[http://spaf.cerias.purdue.edu/][Eugene H. Spafford]].

** M.S. in Computer Science
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: West Lafayette, IN, U.S.A.
:SCHOOL: Purdue University
:FROM: <1996-08-01>
:TO: <1998-05-01>
:END:

- Advisor: [[http://spaf.cerias.purdue.edu/][Eugene H. Spafford]].

** Bachelor's degree in Computer Engineering
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: Mexico City, Mexico
:SCHOOL: National Autonomous University of Mexico (UNAM)
:FROM: <1989-08-01>
:TO: <1995-07-01>
:END:

- Thesis title: [[https://zzamboni.org/files/theses/zamboni-bachelors-thesis.pdf][UNAM/Cray Project for Security in the Unix Operating System]] (in Spanish, original title: /Proyecto UNAM/Cray de Seguridad en el Sistema Operativo Unix/).

* Certifications
:PROPERTIES:
:CV_ENV:   cventries
:END:

** [[https://www.youracclaim.com/badges/98814af3-575b-4350-9667-70eddfea1da4/public_url][Certified Information Systems Security Professional (CISSP)]]
:PROPERTIES:
:CV_ENV:   cvschool
:ORGANIZATION: (ISC)², the International Information System Security Certification Consortium
:LOCATION: April 2019
:RIGHT_IMG: ./images/certified-information-systems-security-professional-cissp-large.png
:END:

#+begin_cvitems
The vendor-neutral CISSP credential confirms technical knowledge and experience to design, engineer, implement, and manage the overall security posture of an organization. Required by the world’s most security-conscious organizations, CISSP is the gold-standard information security certification that assures information security leaders possess the breadth and depth of knowledge to establish holistic security programs that protect against threats in an increasingly complex cyber world.
#+end_cvitems

** [[https://www.youracclaim.com/badges/e6bf0ca2-f1c4-4af6-bf63-09f4b8cdbd02/public_url][SAFe\reg 4 Certified Product Owner/Product Manager]]
:PROPERTIES:
:CV_ENV:   cvschool
:ORGANIZATION: Scaled Agile Inc.
:LOCATION: July 2017
:RIGHT_IMG: ./images/certified-safe-4-product-owner-product-manager-large.png
:END:

#+begin_cvitems
A SAFe\reg 4 Certified Product Owner/Product Manager is a SAFe professional who works with customers and development organizations to identify and write requirements. Key areas of competency include identifying customer needs, writing epics, capabilities, features, stories, and prioritizing work in order to effectively deliver value to the enterprise.
#+end_cvitems

* System Development and Management
:PROPERTIES:
:CV_ENV:   cvskills
:END:

- Programming languages :: C, Perl, Java, AWK, Unix shells (Elvish shell, Bourne shell, C shell, Korn shell), Python, PHP, Ruby, Objective~C, Cocoa (MacOS X), Go, Clojure.
- Development environments :: Unix/Linux, OpenStack, Cloud Foundry, Amazon EC2, Mac OS X.
- Unix system administration :: Linux (experience with multiple distributions including RedHat, Ubuntu, Debian, Gentoo, and others), OpenBSD, FreeBSD, MacOS X, MacOS X Server, Solaris.
- Configuration management :: CFEngine 3, Puppet, Chef, Ansible.
- Virtualization, containers and cloud :: VMWare (ESX, vSphere), OpenStack, Amazon EC2, Docker, Cloud Foundry.
- Health Management and Monitoring :: VMware vRealize Operations Manager, vRealize Log Insight, Nagios, Icinga.
- Other :: REST APIs, Riemann (event stream processing), XML and related technologies, network programming, database programming (SQL), kernel programming (OpenBSD and Linux), HTML.

* Software Development Projects

** Publicly-available software projects: see [[https://github.com/zzamboni/][https://github.com/zzamboni/]]

** Other software projects (not publicly available)

*** Pilatus (IBM)
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: 2005
:TO: 2007
:END:

A system installer that allows arbitrary system installation and configurations, allowing for both proprietary and open source components to be installed in an automated fashion. Open source components can be downloaded directly from their original source to avoid distributing them.

*** SOC in a Box (IBM)
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: 2005
:TO: 2007
:END:

A specialized Linux distribution containing multiple security services for integrated security monitoring in small and medium networks. Implementation includes also backend infrastructure components for system installation, configuration and upgrade; and data centralization, analysis and reporting.

*** Billy Goat (IBM)
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: 2002
:TO: 2007
:END:

A specialized Linux distribution containing multiple sensors for detection of large-scale automated attacks. Implementation includes also backend infrastructure components for system configuration and upgrade, data centralization, analysis and reporting.

*** Embedded Sensors Project (ESP)
:PROPERTIES:
:CV_ENV:   cvsubentry
:FROM: 1999
:TO: 2001
:END:

A system of sensors for intrusion detection developed in OpenBSD through code instrumentation. Developed as part of my Ph.D. thesis work. Programming done mostly in C.

* References

#+latex: \begin{cvparagraph}
Available by request.
#+latex: \end{cvparagraph}

* Local Variables :ARCHIVE:noexport:
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda () (org-export-to-file 'awesomecv "zamboni-vita.tex")) :append :local)
# End:
